# Minimal Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: brittni and the polar bear - code + art boutique
description: stationery + gifts created from original algorithmic art ğŸ’œğŸ‘©ğŸ½â€ğŸ’»ğŸ¨
logo: assets/img/logo.png
show_downloads: false
