# Minima theme configuration
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

title: brittni and the polar bear - code + art boutique
description: stationery + gifts created from original algorithmic art ğŸ’œğŸ‘©ğŸ½â€ğŸ’»ğŸ¨
logo: assets/images/logo.png
show_downloads: false
